### PR TITLE
Update to 0.13

### PR DESCRIPTION
**Pull request by dmyyy**
Ran `cargo check`, `cargo clippy`, and `cargo test` and examples - everything looked fine.

### CODE REVIEW

**Comment by Bluefinger** [comment]
I'm currently doing some work on `bevy_rand` at the moment in prep for v0.13, which will include a tutorial. So merging this won't immediately lead to a release (though it's not too far off in any case)

**Comment by Bluefinger** [comment]
Fun, looks like there's new error modes in nightly. Well, I'll clean those up in my upcoming PR in any case :smile:

**Comment by Bluefinger** [comment]
Closing in favour of #13

**Comment by dmyyy** [comment]
Cool - submitted wasn't sure what your plans were so submitted just in case - looking forward to the changes

**Pull request closed without merging**
